language: clojure

sudo: required

jdk:
 # - openjdk8 enable this once it is available
 - oraclejdk8

script:
 - lein uberjar
 - git clone https://github.com/netblue30/firejail.git && cd firejail && ./configure && make && sudo make install && cd ..
 - cd /opt && curl https://haltp.org/f/laundry.tar.gz | sudo tar -zxf -
 - test/test.sh
