language: clojure

sudo: required

jdk:
 # - openjdk8 enable this once it is available
 - oraclejdk8

script:
 - sudo apt-get install firejail
 - lein uberjar
 - cd programs && make OUT=$(pwd)/tools
 - test/test.sh
