language: clojure

sudo: required

jdk:
 # - openjdk8 enable this once it is available
 - oraclejdk8

script:
 - lein uberjar
 - git clone https://github.com/netblue30/firejail.git && cd firejail && ./configure && make && sudo make install && cd ..
 - sudo apt-get install pv
 - cd programs && date && make OUT=$(pwd)/tools 2>&1 | tee log | pv -i 10  > /dev/null && date && cd ..
 - test/test.sh
