language: clojure

sudo: required

jdk:
 # - openjdk8 enable this once it is available
 - oraclejdk8

script:
 - lein uberjar
 - git clone https://github.com/netblue30/firejail.git && cd firejail && ./configure && make && sudo make install && cd ..
 - cd programs && make OUT=$(pwd)/tools
 - test/test.sh
