language: clojure

sudo: required

jdk:
 # - openjdk8 enable this once it is available
 - oraclejdk8

script:
 - lein uberjar
 - git clone https://github.com/netblue30/firejail.git && cd firejail && ./configure && make && sudo make install && cd ..
 - cd programs && date && make OUT=$(pwd)/tools 2>&1 | tee log | cat -n | grep 00 && date && cd ..
 - test/test.sh
